load("@crates//:defs.bzl", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_binary(
    name = "build-bundle",
    srcs = glob(["src/bin/*.rs"]),
    crate_root = "src/bin/build_bundle.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = [
        ":foe_lineage",
        "//crates/program:foe_program",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_binary(
    name = "check-ancestry",
    srcs = ["examples/check_ancestry.rs"],
    crate_root = "examples/check_ancestry.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = [":foe_lineage"] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_binary(
    name = "source-adoption",
    srcs = ["examples/source_adoption.rs"],
    crate_root = "examples/source_adoption.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = [
        ":foe_lineage",
        "//crates/log:foe_log",
        "//crates/program:foe_program",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_library(
    name = "foe_lineage",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "foe_lineage",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/program:foe_program",
        "//crates/log:foe_log",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
