load("@crates//:defs.bzl", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library")

filegroup(
    name = "self_extension_sources",
    srcs = [
        "src/read.rs",
        "src/read_test.rs",
    ],
    visibility = ["//examples/self-extension:__pkg__"],
)

rust_library(
    name = "foe_code",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["exec"],
    crate_name = "foe_code",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/config:foe_config",
        "//crates/core:foe_core",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
