load("@crates//:defs.bzl", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "foe_program",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["src/schema.json"],
    crate_name = "foe_program",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    version = "0.1.0",
    visibility = ["//visibility:public"],
    deps = ["//crates/log:foe_log"] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
