load("@crates//:defs.bzl", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "foe_transport",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "api-key",
        "chat",
        "gemini",
        "google",
        "messages",
        "responses",
        "token-file",
    ],
    crate_name = "foe_transport",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    version = "0.2.0",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/contract:foe_contract",
        "//crates/core:foe_core",
        "//crates/log:foe_log",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
