load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "tool_audit_test",
    srcs = ["run_tool_audit.py"],
    args = ["--foe", "$(rootpath //:foe)"],
    data = [
        "responses.py",
        "//evals:host_runtime.py",
        "//python:foe_package",
        "//:foe",
    ],
    size = "small",
)

sh_test(
    name = "tool_audit_unit_test",
    srcs = ["run_tool_audit_unit_tests.sh"],
    data = [
        "responses.py",
        "run_tool_audit.py",
        "tool_audit_test.py",
    ],
    size = "small",
)
